INSERT ALL
 INTO "shopping" ("sh_id", "sh_transaction", "sh_category")
  VALUES (1, 1, N'Сумка')
 INTO "shopping" ("sh_id", "sh_transaction", "sh_category")
  VALUES(2, 1, N'Платье')
 INTO "shopping" ("sh_id", "sh_transaction", "sh_category")
  VALUES(3, 1, N'Сумка')
 INTO "shopping" ("sh_id", "sh_transaction", "sh_category")
  VALUES(4, 2, N'Сумка')
 INTO "shopping" ("sh_id", "sh_transaction", "sh_category")
  VALUES(5, 2, N'Юбка')
 INTO "shopping" ("sh_id", "sh_transaction", "sh_category")
  VALUES(6, 3, N'Платье')
 INTO "shopping" ("sh_id", "sh_transaction", "sh_category")
  VALUES(7, 3, N'Юбка')
 INTO "shopping" ("sh_id", "sh_transaction", "sh_category")
  VALUES(8, 3, N'Туфли')
 INTO "shopping" ("sh_id", "sh_transaction", "sh_category")
  VALUES(9, 3, N'Шляпка')
 INTO "shopping" ("sh_id", "sh_transaction", "sh_category")
  VALUES(10, 4, N'Сумка')
SELECT 1 FROM "DUAL";