INSERT ALL
 INTO "shopping" ("sh_id", "sh_transaction", "sh_category")
  VALUES (1, 1, N'Bag')
 INTO "shopping" ("sh_id", "sh_transaction", "sh_category")
  VALUES(2, 1, N'Dress')
 INTO "shopping" ("sh_id", "sh_transaction", "sh_category")
  VALUES(3, 1, N'Bag')
 INTO "shopping" ("sh_id", "sh_transaction", "sh_category")
  VALUES(4, 2, N'Bag')
 INTO "shopping" ("sh_id", "sh_transaction", "sh_category")
  VALUES(5, 2, N'Skirt')
 INTO "shopping" ("sh_id", "sh_transaction", "sh_category")
  VALUES(6, 3, N'Dress')
 INTO "shopping" ("sh_id", "sh_transaction", "sh_category")
  VALUES(7, 3, N'Skirt')
 INTO "shopping" ("sh_id", "sh_transaction", "sh_category")
  VALUES(8, 3, N'Shoes')
 INTO "shopping" ("sh_id", "sh_transaction", "sh_category")
  VALUES(9, 3, N'Hat')
 INTO "shopping" ("sh_id", "sh_transaction", "sh_category")
  VALUES(10, 4, N'Bag')
SELECT 1 FROM "DUAL";